# -*- coding: utf-8 -*-
"""class notes (Q.1-25)    4/2/26, 11/2/26    .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qc-rs3EuH9algMN2qW8bfF5or61dq5gp
"""

#Q1.
n = int(input("Enter number of digits: "))
s = 0

for i in range(n):
    d = int(input("Enter digit: "))
    s = s + d

print("Sum =", s)

#Q2
n = int(input("Enter number of digits: "))
p = 1

for i in range(n):
    d = int(input("Enter digit: "))
    p = p * d

print("Product =", p)

#Q3
num = int(input("Enter number: "))
reversed_num = 0

while num > 0:
    d = num % 10
    reversed_num = reversed_num * 10 + d
    num //= 10

print("Reversed number =", reversed_num)

#Q4
num = int(input("Enter number: "))
original = num
rev = 0

while num > 0:
    d = num % 10
    rev = rev * 10 + d
    num //= 10

if rev == original:
    print("Palindrome number")
else:
    print("Not a palindrome number")

#Q5
num = int(input("Enter number: "))
original = num
temp = num

n = 0
while temp > 0:
    n += 1
    temp //= 10

arm = 0
temp = num
while temp > 0:
    d = temp % 10
    arm += d ** n
    temp //= 10

if arm == original:
    print("Armstrong number")
else:
    print("Not an Armstrong number")

#Q6
n = int(input("Enter number: "))
sum_div = 0

for i in range(1, n):
    if n % i == 0:
        sum_div += i

if sum_div == n:
    print("Perfect Number")
else:
    print("Not Perfect Number")

#Q7
import math

n = int(input("Enter number: "))
temp = n
sum_fact = 0

while temp > 0:
    digit = temp % 10
    sum_fact += math.factorial(digit)
    temp //= 10

if sum_fact == n:
    print("Strong Number")
else:
    print("Not Strong Number")

#Q8
n = int(input("Enter number: "))
temp = n
sum_digits = 0

while temp > 0:
    sum_digits += temp % 10
    temp //= 10

if n % sum_digits == 0:
    print("Harshad Number")
else:
    print("Not Harshad Number")

#Q9
n = int(input("Enter number: "))
square = n * n

if str(square).endswith(str(n)):
    print("Automorphic Number")
else:
    print("Not Automorphic Number")

#Q10
n = int(input("Enter number: "))
square = n * n
sum_digits = 0

while square > 0:
    sum_digits += square % 10
    square //= 10

if sum_digits == n:
    print("Neon Number")
else:
    print("Not Neon Number")

#Q11
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

while b != 0:
    a, b = b, a % b

print("GCD =", a)

#Q12
def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

lcm = (a * b) // gcd(a, b)
print("LCM =", lcm)

#Q13
def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))

hcf = gcd(gcd(a, b), c)
print("HCF =", hcf)

#Q14
a = int(input("Enter base: "))
b = int(input("Enter exponent: "))

result = 1
for i in range(b):
    result *= a

print("Result =", result)

#Q15
a = int(input("Enter base: "))
b = int(input("Enter exponent: "))
m = int(input("Enter mod: "))

result = 1
a = a % m

while b > 0:
    if b % 2 == 1:
        result = (result * a) % m
    a = (a * a) % m
    b //= 2

print("Result =", result)

#Q16
n = int(input("Enter number: "))
i = 2

while i * i <= n:
    while n % i == 0:
        print(i, end=" ")
        n //= i
    i += 1

if n > 1:
    print(n)

#Q17
n = int(input("Enter number: "))

if n <= 1:
    print("Not Prime")
else:
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            print("Not Prime")
            break
    else:
        print("Prime")

#Q18
n = int(input("Find primes up to: "))
prime = [True] * (n + 1)

p = 2
while p * p <= n:
    if prime[p]:
        for i in range(p * p, n + 1, p):
            prime[i] = False
    p += 1

for i in range(2, n + 1):
    if prime[i]:
        print(i, end=" ")

#Q19
start = int(input("Start: "))
end = int(input("End: "))

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

for i in range(start, end):
    if is_prime(i) and is_prime(i + 2):
        print((i, i + 2))

#Q20
def factorial(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial(n - 1)

n = int(input("Enter number: "))
print("Factorial =", factorial(n))

#Q21
import math

n = int(input("Enter n: "))
r = int(input("Enter r: "))

ncr = math.factorial(n) // (math.factorial(r) * math.factorial(n - r))
print("nCr =", ncr)

#Q22
import math

n = int(input("Enter n: "))
r = int(input("Enter r: "))

npr = math.factorial(n) // math.factorial(n - r)
print("nPr =", npr)

#Q23
n = int(input("Enter n: "))
sum_series = 0

for i in range(1, n + 1):
    sum_series += 1 / i

print("Sum =", sum_series)

#Q24
import math

x = float(input("Enter x (in radians): "))
n = int(input("Enter number of terms: "))

result = 0
for i in range(n):
    term = ((-1)**i * x**(2*i + 1)) / math.factorial(2*i + 1)
    result += term

print("sin(x) =", result)

#Q25
import math

x = float(input("Enter x: "))
n = int(input("Enter number of terms: "))

result = 0
for i in range(n):
    result += (x**i) / math.factorial(i)

print("e^x =", result)