# -*- coding: utf-8 -*-
"""class notes (Q.1-5)    4/2/26     .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qc-rs3EuH9algMN2qW8bfF5or61dq5gp
"""

#Q1.
n = int(input("Enter number of digits: "))
s = 0

for i in range(n):
    d = int(input("Enter digit: "))
    s = s + d

print("Sum =", s)

#Q2
n = int(input("Enter number of digits: "))
p = 1

for i in range(n):
    d = int(input("Enter digit: "))
    p = p * d

print("Product =", p)

#Q3
num = int(input("Enter number: "))
reversed_num = 0

while num > 0:
    d = num % 10
    reversed_num = reversed_num * 10 + d
    num //= 10

print("Reversed number =", reversed_num)

#Q4
num = int(input("Enter number: "))
original = num
rev = 0

while num > 0:
    d = num % 10
    rev = rev * 10 + d
    num //= 10

if rev == original:
    print("Palindrome number")
else:
    print("Not a palindrome number")

#Q5
num = int(input("Enter number: "))
original = num
temp = num

n = 0
while temp > 0:
    n += 1
    temp //= 10

arm = 0
temp = num
while temp > 0:
    d = temp % 10
    arm += d ** n
    temp //= 10

if arm == original:
    print("Armstrong number")
else:
    print("Not an Armstrong number")